### ISSUE TITLE
[BUG] - module 'torch' has no attribute '_six'

### ISSUE THREAD

**Issue by vanilladucky** [pytorch/tutorials#2284] opened 2023-04-13 04:46 UTC
### Add Link

https://pytorch.org/tutorials/beginner/dcgan_faces_tutorial.html

### Describe the bug

When I try to run the data loader section, it keeps returning this error of torch not having the attribute _six. I made sure that my dataroot is right and the files are there but it just doesn't seem to fix the problem. 

### Describe your environment

Mac and PyTorch version 2.0.0

**Comment by svekars** [comment] 2023-04-13 21:30
Thank you for reporting this. I just ran this locally on mac with PyTorch 2.0 as a notebook and I can't reproduce the problem. Can you please post the detailed output of the error you are getting? Also did you run as a notebook or as a python script?

**Comment by vanilladucky** [comment] 2023-04-14 09:22
Absolutely! Apologies for the lack of details.

I believe I'm facing issues with the **dataset.ImageFolder** function portion. 
However, I have followed closely to the tutorial and have nested my data files as instructed. 

My dataroot is as such `dataroot = "../data/celeba/"` where the data directory is stored one level up and inside of that data directory, there is another directory called celeba where I have placed the img_align_celeba folder containing all the image files. 

* data
  * celeba 
    * img_align_celeba
       * images...
       
Additionally, I am running this is as a .ipynb file in vscode. 
The exact error I obtain is as shown below: 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 3
      1 # We can use an image folder dataset the way we have it setup.
      2 # Creating a 
----> 3 dataset = dset.ImageFolder(root=dataroot,
      4                            transform=transforms.Compose([
      5                                transforms.Resize(image_size),
      6                                transforms.CenterCrop(image_size),
      7                                transforms.ToTensor(),
      8                                transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
      9                            ]))
     10 # Create the dataloader
     11 dataloader = torch.utils.data.DataLoader(dataset, batch_size=batch_size,
     12                                          shuffle=True, num_workers=workers)

File ~/Documents/Python/My own project (Python)/machinelearning/lib/python3.10/site-packages/torchvision/datasets/folder.py:309, in ImageFolder.__init__(self, root, transform, target_transform, loader, is_valid_file)
    301 def __init__(
    302     self,
    303     root: str,
   (...)
    307     is_valid_file: Optional[Callable[[str], bool]] = None,
    308 ):
--> 309     super().__init__(
    310         root,
...
---> 39     if isinstance(root, torch._six.string_classes):
     40         root = os.path.expanduser(root)
     41     self.root = root

AttributeError: module 'torch' has no attribute '_six'
```

**Comment by svekars** [comment] 2023-04-14 16:15
I'd try to set the absolute path like ``/Users/user/path/to/celeba/`` for the dataroot and also reset kernel/restart mac and see if it helps.

**Comment by vanilladucky** [comment] 2023-04-15 14:39
Ok so I have tried your approach but it still returned back the same error, even after resetting my kernel and mac, which I thought would work cause I've read similar solutions online. 

However, I have approached it from a different angle by building a custom dataset instead. When I used the absolute path in the custom dataset, the whole notebook worked out perfectly with just a few tweaks in the remaining code in the notebook. 

Although I was able to execute the code smoothly with an alternative approach, I still don't know what exactly is causing this error. I just hope it's a local problem I'm facing and not a global problem with others too. 

**Additionally**, if it's okay to ask about the usage of MPS for Apple chips, can I ask whether there is a significant advantage of utilizing MPS over not utilizing it, because even after setting the device to MPS, the training process still took 108 minutes.

**Comment by albanD** [comment] 2023-04-17 17:28
Hi,

The `_six` module was private and not actually implemented in PT and has been removed as it should not be used. You can use python's regular six module instead.

For MPS, as for any GPU, it will depend on your workload. I would recommend the forum: https://discuss.pytorch.org/ to ask this kind of questions!

**Comment by svekars** [comment] 2023-04-17 21:35
Closing as it looks like all issues are resolved.

**Closed by svekars** 2023-04-17 21:35 UTC
Labels: bug, question

**Comment by intexcor** [comment] 2024-11-20 14:19
torchvision.datasets.CIFAR10(root='cifar', train=False, download=True, transform=cifar_transform
                                              )
                                              
 вызывает ошибку
 AttributeError: module 'torch' has no attribute '_six'

**Comment by intexcor** [comment] 2024-11-20 14:19
@svekars
