### ISSUE TITLE
Multiprocessing Error in TRAINING A CLASSIFIER tutorial

### ISSUE THREAD

**Issue by thutzr** [pytorch/tutorials#1329] opened 2021-02-01 06:07 UTC
Hi, 
I am trying to running the Train A Classifier tutorial but I get some errors when running the codes without any change.  Here is the codes and error.
Codes:
```
import matplotlib.pyplot as plt
import numpy as np
def imshow(img):
    img = img/2 + 0.5
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg,(1,2,0)))
    plt.show()
    
dataiter = iter(trainloader)
images, labels = dataiter.next()
imshoow(torchvision.utils.make_grid(images))

```
Error:
```
ImportError                               Traceback (most recent call last)
<ipython-input-28-812cc55ae342> in <module>
      8 
      9 dataiter = iter(trainloader)
---> 10 images, labels = dataiter.next()
     11 imshoow(torchvision.utils.make_grid(images))

~/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py in __next__(self)
    433         if self._sampler_iter is None:
    434             self._reset()
--> 435         data = self._next_data()
    436         self._num_yielded += 1
    437         if self._dataset_kind == _DatasetKind.Iterable and \

~/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _next_data(self)
   1083             else:
   1084                 del self._task_info[idx]
-> 1085                 return self._process_data(data)
   1086 
   1087     def _try_put_index(self):

~/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py in _process_data(self, data)
   1109         self._try_put_index()
   1110         if isinstance(data, ExceptionWrapper):
-> 1111             data.reraise()
   1112         return data
   1113 

~/anaconda3/lib/python3.8/site-packages/torch/_utils.py in reraise(self)
    426             # have message field
    427             raise self.exc_type(message=msg)
--> 428         raise self.exc_type(msg)
    429 
    430 

ImportError: Caught ImportError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zeren/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zeren/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/zeren/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/zeren/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/zeren/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 53, in default_collate
    storage = elem.storage()._new_shared(numel)
  File "/home/zeren/anaconda3/lib/python3.8/site-packages/torch/storage.py", line 131, in _new_shared
    from torch.multiprocessing import get_sharing_strategy
ImportError: cannot import name 'get_sharing_strategy' from 'torch.multiprocessing' (/home/zeren/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/__init__.py)

```

It seems like it is `torch.multiprocessing` causing these errors. I check torch package and there is module or function named `get_sharing_strategy`. 

I am currently using anaconda and Pytorch 1.7.1. I am not sure if it is that the PyTorch version I am using is too high.  

I am new to PyTorch and I hope someone could give me any help. Thanks a lot.

**Comment by thutzr** [comment] 2021-02-01 06:23
When I change `num_worker ` to 0 in `dataloader`, the error disappears. But I am still confusing why this error occurs. Does it mean there is something wrong with multiprocessing package?

**Comment by Melcfrn** [comment] 2022-06-09 13:29
Hi,
I am late in arriving and probably you found a response to your question.
Could the problem came from you had only 1 core available ?
Or from a similar problem like this https://github.com/pytorch/pytorch/issues/13246#issuecomment-905703662 ?

Clément

**Comment by svekars** [comment] 2023-03-10 15:57
I was not able to reproduce this in Colab with the latest PyTorch version, so closing. Feel free to reopen if you have more questions.

**Closed by svekars** 2023-03-10 15:57 UTC
Labels: 60_min_blitz
