### ISSUE TITLE
ax_multiobjective_nas_tutorial.py is failing against 1.13

### ISSUE THREAD

**Issue by svekars** [pytorch/tutorials#2090] opened 2022-10-20 16:36 UTC
[ax_multiobjective_nas_tutorial.py](https://github.com/pytorch/tutorials/blob/master/intermediate_source/ax_multiobjective_nas_tutorial.py) is failing against 1.13 binaries. More details [here](https://app.circleci.com/pipelines/github/pytorch/tutorials/6772/workflows/e5ee8793-cec0-4a60-a9f5-924e2ad4cea0/jobs/132480?invite=true#step-104-2552). 

We will disable this tutorial until this issue is resolved.

cc: @Balandat @malfet

**Comment by Balandat** [comment] 2022-10-20 17:21
Thanks for the heads up.

This seems to be an issue with TorchX which appears to fail on import? @d4l3k are there known incompatibilities between torchx and torch 1.13 (looks like the torchx version installed in CI is `0.2.0`).

**Comment by Balandat** [comment] 2022-10-20 17:28
cc @dme65, @esantorella

**Comment by d4l3k** [comment] 2022-10-20 17:34
The issue isn't TorchX or torch 1.13 -- importlib_metadata broke backwards compatibility with Python 3.7

https://github.com/python/importlib_metadata/issues/411

We've had to pin <5.0 in trunk https://github.com/pytorch/torchx/blob/main/dev-requirements.txt#L10 to resolve the issue

**Comment by Balandat** [comment] 2022-10-20 17:36
Great, thanks for the quick response. Let me put up a PR to add that pin also to the reqs for the tutorials.

**Comment by Balandat** [comment] 2022-10-21 03:15
@svekars I merged the fix, I assume this can be closed? Or is there anything that needs to be done to re-enable the tutorial?

**Closed** 2023-03-01 23:41 UTC
Labels: 1.13
