### ISSUE TITLE
Sequence to sequence encoder-decoder attention not looking at encoder hidden states

### ISSUE THREAD

**Issue by hotzjacobb** [pytorch/tutorials#2121] opened 2022-11-16 22:09 UTC
Hi,

I believe that the [code/notebook example](https://github.com/pytorch/tutorials/blob/master/intermediate_source/seq2seq_translation_tutorial.py) of a sequence to sequence model that uses attention should be changed.

Attention (as described in [Bahdanau 2014](https://arxiv.org/abs/1409.0473)) serves as a mechanism for looking at encoder hidden states (now often referred to as cross-attention when talking about Transformers). Theoretically, its justification is that it allows a variable size representation of information depending on input sequence length (which is variable), so that there is not a representation bottleneck at the output of the final hidden layer for the encoder.

The tutorial/code currently computes attention by using the decoder's hidden state after the first input and the embedding of the decoder's first output. I believe that this is incorrect. 

I think it should instead be using the decoder's prior hidden state and the encoder's hidden states so that the model knows what to focus on from the input sequence for the current timestep of the decoder's output.

I can submit a PR to change this in the tutorial if correct; thanks.

cc @pytorch/team-text-core @Nayef211

**Comment by Nayef211** [comment] 2022-12-07 20:56
Hi @hotzjacobb, thanks for submitting this issue. I think this may be a duplicate of https://github.com/pytorch/tutorials/issues/130#issuecomment-605616535. Happy to review your PR if you want to take a stab at fixing this!

**Comment by JoseLuisC99** [comment] 2023-06-02 20:37
As mentioned in #130, this tutorial requires big changes. Can I rework some functions to make it more readable or it is out of scope of the docathon?

**Closed** 2023-06-14 19:51 UTC
Labels: module: torchtext, docathon-h1-2023, medium
