### ISSUE TITLE
Dynamic quantization tutorial has a bug when calling the glue_convert_examples_to_features function

### ISSUE THREAD

**Issue by millenialSpirou** [pytorch/tutorials#1431] opened 2021-03-21 02:40 UTC
- I'm trying to reproduce the following tutorial: https://pytorch.org/tutorials/intermediate/dynamic_quantization_bert_tutorial.html

- Right now the tutorial is not reproducible on my machine by following the instructions

- The traceback it gives is 
Traceback (most recent call last):
  File "/home/fredericb/udem/nlp/project/code/tutorial.py", line 244, in <module>
    time_model_evaluation(model, configs, tokenizer)
  File "/home/fredericb/udem/nlp/project/code/tutorial.py", line 237, in time_model_evaluation
    result = evaluate(configs, model, tokenizer, prefix="")
  File "/home/fredericb/udem/nlp/project/code/tutorial.py", line 104, in evaluate
    eval_dataset = load_and_cache_examples(args, eval_task, tokenizer, evaluate=True)
  File "/home/fredericb/udem/nlp/project/code/tutorial.py", line 188, in load_and_cache_examples
    features = convert_examples_to_features(examples,
TypeError: glue_convert_examples_to_features() got an unexpected keyword argument 'pad_on_left'

- The glu_convert_examples_to_features is called in the load_and_cache_examples function as follows:

```python
        features = convert_examples_to_features(examples,
                                                tokenizer,
                                                label_list=label_list,
                                                max_length=args.max_seq_length,
                                                output_mode=output_mode,
                                                pad_on_left=bool(args.model_type in ['xlnet']),                 # pad on the left for xlnet
                                                pad_token=tokenizer.convert_tokens_to_ids([tokenizer.pad_token])[0],
                                                pad_token_segment_id=4 if args.model_type in ['xlnet'] else 0,
        )
```

In the tutorial it is mentionned that the functions evaluate and load_and_cache_examples are taken from the huggingface library but the link pointing to their definition is broken and I can't figure out what the equivalent code would be in the huggingface repos. From the doc it looks like the closest equivalent would be some methods in the Trainer class: https://huggingface.co/transformers/main_classes/trainer.html

cc @jerryzh168 @jianyuh

**Comment by soumendukrg** [comment] 2022-05-27 17:06
I was able to run this file while commenting out the last 3 arguments, `pad_on_left`, `pad_token`, `pad_token_segment_id`.

**Comment by svekars** [comment] 2023-03-09 19:36
duplicate of https://github.com/pytorch/tutorials/issues/1406

**Closed by svekars** 2023-03-09 19:36 UTC
Labels: module: quantization
