### ISSUE TITLE
problem when runs mario_rl_tutorial.py 

### ISSUE THREAD

**Issue by azyslzp** [pytorch/tutorials#1292] opened 2020-12-23 18:14 UTC
When I run the _mario_rl_tutorial.py_, I met the problem as follows:

  File "D:\anaconda35\lib\site-packages\matplotlib\backends\backend_agg.py", line 526, in print_png
    self.figure.dpi, metadata=metadata)

TypeError: Object does not appear to be a 8-bit string path or a Python file-like object

How could I solve that? Thanks a lot~

cc @vmoens @nairbv

**Comment by songyuc** [comment] 2021-01-21 05:57
I cannot run this repo, as decribed in https://github.com/YuansongFeng/MadMario/issues/6.

**Comment by svekars** [comment] 2023-03-10 18:31
I was not able to reproduce with the latest PyTorch, can you try with the latest PyTorch and see if this is still an issue? Closing for now.

**Closed by svekars** 2023-03-10 18:31 UTC
Labels: rl
