### ISSUE TITLE
The input of a GRU is of shape (seq_len, batch, input_size). I wonder does seq_len means anything?

### ISSUE THREAD

**Issue by AllenIverSunn** [pytorch/tutorials#463] opened 2019-04-02 09:32 UTC
I noticed that in the documentation of pytorch GRU, the input shape should be (seq_len, batch, input_size), thus the input ought to be a sequence and the model will deal with the sequence inside itself. But in this notebook, the author passes a tensor only of length one in each iteration in function `train`. I mean if the model can deal with sequential inputs, why not just feed a sequence of sentence to it?

This is my first time to start an issue on github, please forgive me if there is anything wrong.

**Comment by jlin27** [comment] 2019-08-23 21:49
Closing as this is a duplicate of this issue: https://github.com/pytorch/tutorials/issues/464

**Closed by jlin27** 2019-08-23 21:49 UTC
